# Generated by Django 4.0.5 on 2022-08-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflix',
            name='date_added',
            field=models.DateTimeField(max_length=36),
        ),
    ]
