# Generated by Django 4.0.6 on 2022-08-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonflix', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Netflix',
        ),
    ]
