# Generated by Django 4.0.5 on 2022-08-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonflix', '0003_alter_netflix_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflix',
            name='date_added',
            field=models.DateField(blank=True, max_length=36, null=True),
        ),
    ]
