name: Django CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: 'Create env file'
        run: |
          touch .env
          echo DEBUG=True >> .env
          echo SECRET_KEY="[Fa?7Gutf^NuL9C'j3a#},f%]x2d@u" >> .env
          echo POSTGRES_DB=netflix >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=postgres >> .env
          echo POSTGRES_HOST=localhost >> .env
          echo POSTGRES_PORT=5432 >> .env
          cat .env
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Application tests with Pytest
      run: |
        pytest
