name: Django CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_POSTGRES_DB: netflix
        envkey_POSTGRES_USER: postgres
        envkey_POSTGRES_PASSWORD: postgres
        envkey_POSTGRES_HOST: localhost
        env_key_POSTGRES_PORT: 5432
        file_name: .env
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Application tests with Pytest
      run: |
        pytest
